version: "3.8"
services:
    db: 
      image: postgres:latest
      restart: always
      volumes: 
      - ./data/db:/var/lib/postgresql/data
      ports: 
      - 5431:5432

      environment:
        POSTGRES_DB: root
        POSTGRES_USER: tanvir
        POSTGRES_PASSWORD: iamthevest
  
    adminer:
      image: adminer:latest
      restart: always 
      ports:
        - 8080:8080

