# Generated by Django 5.1.6 on 2025-02-15 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productinventory_productreviews_producttags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productInventory',
            new_name='productCertificate',
        ),
    ]
