# Generated by Django 5.1.6 on 2025-02-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_producttags_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='productTea',
            new_name='product_tea',
        ),
        migrations.RemoveField(
            model_name='productcertificate',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
